# Generated by Django 2.0.3 on 2018-03-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': '条目'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '主题'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Topic', verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
    ]
