# Generated by Django 2.0.3 on 2018-03-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20180331_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='XiaoMing', max_length=30, verbose_name='创建者'),
        ),
    ]
