# Generated by Django 2.0.3 on 2018-03-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20180331_2303'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='entry',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
