# Generated by Django 2.0.3 on 2018-05-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0018_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='search_content',
            new_name='text',
        ),
    ]
