# Generated by Django 2.0.3 on 2018-05-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0019_auto_20180505_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='num',
            field=models.IntegerField(default=1, max_length=11, verbose_name='搜索次数'),
        ),
    ]
