# Generated by Django 2.0.3 on 2018-05-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0020_history_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='num',
            field=models.IntegerField(default=1, verbose_name='搜索次数'),
        ),
    ]
