# Generated by Django 2.0.3 on 2018-04-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180420_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAlive',
            field=models.BooleanField(default=True, verbose_name='用户状态'),
        ),
    ]
