# Generated by Django 2.0.3 on 2018-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180420_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isAlive',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='用户状态'),
        ),
    ]
