# Generated by Django 2.0.3 on 2018-05-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180420_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': '用户'},
        ),
    ]
